# -*- coding: utf-8 -*-
"""detected_plant.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_6ninYGG6ZBcZcq0aOb-qfV79iuUCjln

# 🌱 Intelligent Plant Disease Detection System

این نسخه شامل:
1. **Data Cleaning** — حذف تصاویر خراب/غیرقابل‌خواندن و duplicateهای دقیق
2. **Train/Validation Split**
3. **Classification با YOLOv8 Classification**
4. **Confusion Matrix + Accuracy + Precision + Recall + F1**
5. **Localization تقریبی ضایعات با image processing**
6. **Severity Estimation تقریبی**
7. **Gradio Dashboard**

> نکته: دیتاست PlantVillage برای این پروژه برچسب bounding-box/mask و severity ground-truth ندارد؛ بنابراین Localization و Severity در این نسخه heuristic هستند.

## 0) نصب کتابخانه‌ها
"""

!pip install -q ultralytics opencv-python kaggle gradio scikit-learn seaborn pandas matplotlib pillow

"""## 1) Import و تنظیمات"""

import os, glob, shutil, random, json, warnings, hashlib
import numpy as np
import pandas as pd
import cv2
import matplotlib.pyplot as plt
import seaborn as sns
from PIL import Image
from ultralytics import YOLO
from sklearn.metrics import (
    confusion_matrix, classification_report,
    accuracy_score, precision_score, recall_score, f1_score
)

warnings.filterwarnings('ignore')

SEED = 42
random.seed(SEED)
np.random.seed(SEED)

DATASET_PATH = 'plantvillage_dataset'
YOLO_DATASET = 'plant_yolo_dataset'
RUN_NAME = 'plant_disease_final'
MODEL_PATH = f'runs/classify/{RUN_NAME}/weights/best.pt'

IMG_SIZE = 224
EPOCHS = 5
BATCH = 32

print('Ready.')

"""## 2) دریافت دیتاست از Kaggle"""

from google.colab import files

kaggle_dir = '/root/.kaggle'
kaggle_file = os.path.join(kaggle_dir, 'kaggle.json')

if not os.path.exists(kaggle_file):
    print('kaggle.json را آپلود کنید:')
    uploaded = files.upload()

    os.makedirs(kaggle_dir, exist_ok=True)

    if not uploaded:
        raise FileNotFoundError('فایل kaggle.json آپلود نشد.')

    # Get the actual filename that was uploaded (e.g., 'kaggle (3).json')
    uploaded_filename = list(uploaded.keys())[0]

    if 'kaggle.json' not in uploaded_filename:
        print("هشدار: فایل آپلود شده '{}' نام مورد انتظار 'kaggle.json' را ندارد. با این وجود، به عنوان فایل Kaggle استفاده می‌شود.".format(uploaded_filename))

    shutil.copy(uploaded_filename, kaggle_file)
    os.chmod(kaggle_file, 0o600)

print('Kaggle آماده است.')

!kaggle datasets download -d abdallahalidev/plantvillage-dataset
!unzip -q -o plantvillage-dataset.zip -d plantvillage_dataset

source_class_folders_dir = os.path.join(
    DATASET_PATH, 'plantvillage dataset', 'color'
)

if not os.path.isdir(source_class_folders_dir):
    raise FileNotFoundError(
        f'مسیر دیتاست پیدا نشد: {source_class_folders_dir}'
    )

class_names = sorted([
    d for d in os.listdir(source_class_folders_dir)
    if os.path.isdir(os.path.join(source_class_folders_dir, d))
])

print(f'Number of classes: {len(class_names)}')
print(class_names)

"""## 3) Data Cleaning — پاک‌سازی داده‌ها"""

# این مرحله:
# 1) تصاویر خراب/غیرقابل‌خواندن را حذف می‌کند.
# 2) فایل‌های با پسوند نامعتبر را کنار می‌گذارد.
# 3) duplicateهای دقیق را بر اساس MD5 حذف می‌کند.
# 4) تعداد تصاویر سالم هر کلاس را گزارش می‌کند.

CLEAN_DATASET = 'plantvillage_clean'

if os.path.exists(CLEAN_DATASET):
    shutil.rmtree(CLEAN_DATASET)

os.makedirs(CLEAN_DATASET, exist_ok=True)

VALID_EXTENSIONS = ('.jpg', '.jpeg', '.png', '.bmp', '.webp')

clean_stats = []
global_hashes = set()

for class_name in class_names:
    src_dir = os.path.join(source_class_folders_dir, class_name)
    dst_dir = os.path.join(CLEAN_DATASET, class_name)
    os.makedirs(dst_dir, exist_ok=True)

    total = 0
    kept = 0
    bad = 0
    duplicate = 0

    image_paths = [
        p for p in glob.glob(os.path.join(src_dir, '*'))
        if p.lower().endswith(VALID_EXTENSIONS)
    ]

    for src_path in image_paths:
        total += 1

        # بررسی قابل خواندن بودن تصویر
        img = cv2.imread(src_path)
        if img is None or img.size == 0:
            bad += 1
            continue

        # حذف duplicate دقیق
        with open(src_path, 'rb') as f:
            file_hash = hashlib.md5(f.read()).hexdigest()

        if file_hash in global_hashes:
            duplicate += 1
            continue

        global_hashes.add(file_hash)

        dst_path = os.path.join(dst_dir, os.path.basename(src_path))
        shutil.copy2(src_path, dst_path)
        kept += 1

    clean_stats.append({
        'class': class_name,
        'total': total,
        'kept': kept,
        'bad_images': bad,
        'duplicates': duplicate
    })

clean_df = pd.DataFrame(clean_stats)

print('Cleaning finished.')
print(f'Total images before cleaning: {clean_df["total"].sum()}')
print(f'Images kept: {clean_df["kept"].sum()}')
print(f'Bad images removed: {clean_df["bad_images"].sum()}')
print(f'Duplicates removed: {clean_df["duplicates"].sum()}')

display(clean_df)

# کلاس‌هایی که بعد از cleaning تصویر ندارند
empty_classes = clean_df.loc[clean_df['kept'] == 0, 'class'].tolist()
if empty_classes:
    print('Empty classes:', empty_classes)
    raise ValueError('بعضی کلاس‌ها بعد از cleaning هیچ تصویر سالمی ندارند.')

"""## 4) ساخت Train / Validation از داده‌های Clean شده"""

if os.path.exists(YOLO_DATASET):
    shutil.rmtree(YOLO_DATASET)

os.makedirs(os.path.join(YOLO_DATASET, 'train'), exist_ok=True)
os.makedirs(os.path.join(YOLO_DATASET, 'val'), exist_ok=True)

split_stats = []

for class_name in class_names:
    src = os.path.join(CLEAN_DATASET, class_name)

    images = [
        f for f in glob.glob(os.path.join(src, '*'))
        if f.lower().endswith(VALID_EXTENSIONS)
    ]

    random.Random(SEED).shuffle(images)

    if len(images) < 2:
        raise ValueError(
            f'کلاس {class_name} کمتر از 2 تصویر دارد و برای train/val مناسب نیست.'
        )

    split = int(0.8 * len(images))
    split = max(1, min(split, len(images) - 1))

    train_images = images[:split]
    val_images = images[split:]

    for split_name, split_images in [
        ('train', train_images),
        ('val', val_images)
    ]:
        dst = os.path.join(YOLO_DATASET, split_name, class_name)
        os.makedirs(dst, exist_ok=True)

        for img in split_images:
            shutil.copy2(img, dst)

    split_stats.append({
        'class': class_name,
        'train': len(train_images),
        'val': len(val_images)
    })

split_df = pd.DataFrame(split_stats)

print('Dataset prepared.')
print('Train:', split_df['train'].sum())
print('Validation:', split_df['val'].sum())
display(split_df)

"""## 5) Classification با YOLOv8"""

model = YOLO('yolov8n-cls.pt')

results = model.train(
    data=YOLO_DATASET,
    epochs=20,
    imgsz=IMG_SIZE,
    batch=BATCH,
    name=RUN_NAME,
    patience=3,
    optimizer='AdamW',
    lr0=0.001,
    seed=SEED,
    augment=True,
    device=0
)

print('Training finished.')

best_model = YOLO(MODEL_PATH)
print('Loaded:', MODEL_PATH)

"""## 6) ارزیابی مدل + Confusion Matrix"""

val_root = os.path.join(YOLO_DATASET, 'val')

val_paths = []
y_true = []
y_pred = []
y_conf = []

class_to_id = {name: i for i, name in enumerate(class_names)}

for true_name in class_names:
    folder = os.path.join(val_root, true_name)

    paths = [
        p for p in glob.glob(os.path.join(folder, '*'))
        if p.lower().endswith(VALID_EXTENSIONS)
    ]

    val_paths.extend(paths)

print('Validation images:', len(val_paths))

for img_path in val_paths:
    r = best_model(img_path, verbose=False)[0]

    pred_id = int(r.probs.top1)
    conf = float(r.probs.top1conf)

    true_name = os.path.basename(os.path.dirname(img_path))

    y_true.append(class_to_id[true_name])
    y_pred.append(pred_id)
    y_conf.append(conf)

# معیارهای کلی
acc = accuracy_score(y_true, y_pred)
prec = precision_score(y_true, y_pred, average='weighted', zero_division=0)
rec = recall_score(y_true, y_pred, average='weighted', zero_division=0)
f1 = f1_score(y_true, y_pred, average='weighted', zero_division=0)

print(f'Accuracy : {acc:.4f}')
print(f'Precision: {prec:.4f}')
print(f'Recall   : {rec:.4f}')
print(f'F1-score : {f1:.4f}')

# Confusion Matrix

cm = confusion_matrix(
    y_true,
    y_pred,
    labels=list(range(len(class_names)))
)

plt.figure(
    figsize=(
        max(12, len(class_names) * 0.45),
        max(10, len(class_names) * 0.40)
    )
)

sns.heatmap(
    cm,
    annot=False,
    cmap='Blues',
    xticklabels=class_names,
    yticklabels=class_names
)

plt.xlabel('Predicted label')
plt.ylabel('True label')
plt.title('Confusion Matrix - Plant Disease Classification')
plt.xticks(rotation=90)
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

print('Classification Report:')
print(
    classification_report(
        y_true,
        y_pred,
        target_names=class_names,
        zero_division=0
    )
)

"""## 7) نمایش چند پیش‌بینی اشتباه"""

wrong = [
    (p, t, pr, c)
    for p, t, pr, c in zip(val_paths, y_true, y_pred, y_conf)
    if t != pr
]

print('Wrong predictions:', len(wrong))

n = min(12, len(wrong))

if n:
    sample_wrong = random.sample(wrong, n)

    plt.figure(figsize=(16, 10))

    for i, (path, true_id, pred_id, conf) in enumerate(sample_wrong):
        img = cv2.cvtColor(cv2.imread(path), cv2.COLOR_BGR2RGB)

        ax = plt.subplot(3, 4, i + 1)
        ax.imshow(img)
        ax.set_title(
            f'True: {class_names[true_id]}\n'
            f'Pred: {class_names[pred_id]} ({conf:.1%})',
            fontsize=8
        )
        ax.axis('off')

    plt.tight_layout()
    plt.show()

"""## 8) Localization تقریبی"""

def estimate_leaf_mask(image_bgr):
    hsv = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2HSV)

    mask_green = cv2.inRange(
        hsv,
        np.array([20, 25, 25]),
        np.array([100, 255, 255])
    )

    kernel = np.ones((7, 7), np.uint8)

    mask = cv2.morphologyEx(
        mask_green,
        cv2.MORPH_CLOSE,
        kernel,
        iterations=2
    )

    mask = cv2.morphologyEx(
        mask,
        cv2.MORPH_OPEN,
        kernel,
        iterations=1
    )

    return mask


def estimate_lesion_mask(image_bgr, leaf_mask):
    hsv = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2HSV)
    h, s, v = cv2.split(hsv)

    brown = (
        (h >= 5) & (h <= 25) &
        (s >= 60) & (v <= 210)
    ).astype(np.uint8) * 255

    dark = (
        (v <= 75) & (s >= 25)
    ).astype(np.uint8) * 255

    yellow = (
        (h >= 20) & (h <= 38) &
        (s >= 70) & (v >= 80)
    ).astype(np.uint8) * 255

    lesion = cv2.bitwise_or(brown, dark)
    lesion = cv2.bitwise_or(lesion, yellow)
    lesion = cv2.bitwise_and(lesion, leaf_mask)

    kernel = np.ones((5, 5), np.uint8)

    lesion = cv2.morphologyEx(
        lesion,
        cv2.MORPH_OPEN,
        kernel
    )

    lesion = cv2.morphologyEx(
        lesion,
        cv2.MORPH_CLOSE,
        kernel
    )

    return lesion


def localize_lesions(image_bgr):
    leaf = estimate_leaf_mask(image_bgr)
    lesion = estimate_lesion_mask(image_bgr, leaf)
    return leaf, lesion


def overlay_lesions(image_bgr, lesion_mask):
    out = image_bgr.copy()

    contours, _ = cv2.findContours(
        lesion_mask,
        cv2.RETR_EXTERNAL,
        cv2.CHAIN_APPROX_SIMPLE
    )

    for cnt in contours:
        if cv2.contourArea(cnt) >= 30:
            x, y, w, h = cv2.boundingRect(cnt)
            cv2.rectangle(
                out,
                (x, y),
                (x + w, y + h),
                (0, 0, 255),
                2
            )

    return out

"""## 9) Severity Estimation تقریبی"""

def estimate_severity(image_bgr):
    leaf_mask, lesion_mask = localize_lesions(image_bgr)

    leaf_pixels = np.count_nonzero(leaf_mask)
    lesion_pixels = np.count_nonzero(lesion_mask)

    if leaf_pixels == 0:
        return 0.0, 'Unknown', leaf_mask, lesion_mask

    severity = 100.0 * lesion_pixels / leaf_pixels
    severity = float(np.clip(severity, 0, 100))

    if severity < 10:
        level = 'Mild'
    elif severity < 30:
        level = 'Moderate'
    else:
        level = 'Severe'

    return severity, level, leaf_mask, lesion_mask

"""## 10) تست کامل روی یک تصویر"""

sample_path = random.choice(val_paths)

img_bgr = cv2.imread(sample_path)

r = best_model(sample_path, verbose=False)[0]

pred_id = int(r.probs.top1)
pred_name = r.names[pred_id]
confidence = float(r.probs.top1conf)

severity, severity_level, leaf_mask, lesion_mask = estimate_severity(img_bgr)
overlay = overlay_lesions(img_bgr, lesion_mask)

print('Disease / Class:', pred_name)
print('Confidence:', f'{confidence:.2%}')
print('Estimated Severity:', f'{severity:.2f}%')
print('Severity Level:', severity_level)

plt.figure(figsize=(15, 5))

plt.subplot(1, 3, 1)
plt.imshow(cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB))
plt.title('Original')
plt.axis('off')

plt.subplot(1, 3, 2)
plt.imshow(lesion_mask, cmap='gray')
plt.title('Estimated damaged area')
plt.axis('off')

plt.subplot(1, 3, 3)
plt.imshow(cv2.cvtColor(overlay, cv2.COLOR_BGR2RGB))
plt.title(
    f'{pred_name} | {confidence:.1%} | {severity_level}'
)
plt.axis('off')

plt.tight_layout()
plt.show()

"""## 11) Dashboard با Gradio"""

import gradio as gr

def dashboard_predict(image):
    if image is None:
        return '—', '—', '—', '—', None

    image_rgb = np.array(image).astype(np.uint8)
    image_bgr = cv2.cvtColor(
        image_rgb,
        cv2.COLOR_RGB2BGR
    )

    # Classification
    r = best_model(image_rgb, verbose=False)[0]

    pred_id = int(r.probs.top1)
    pred_name = r.names[pred_id]
    confidence = float(r.probs.top1conf)

    # Localization + severity
    severity, severity_level, leaf_mask, lesion_mask = estimate_severity(
        image_bgr
    )

    overlay = overlay_lesions(
        image_bgr,
        lesion_mask
    )

    overlay_rgb = cv2.cvtColor(
        overlay,
        cv2.COLOR_BGR2RGB
    )

    status = (
        'Healthy'
        if 'healthy' in pred_name.lower()
        else 'Diseased'
    )

    disease_text = f'{pred_name} ({status})'
    confidence_text = f'{confidence:.2%}'
    severity_text = f'{severity:.2f}%'

    return (
        disease_text,
        confidence_text,
        severity_text,
        severity_level,
        overlay_rgb
    )


with gr.Blocks(title='Plant Disease AI') as demo:
    gr.Markdown('# 🌱 Plant Disease AI')
    gr.Markdown(
        'Upload a leaf image to classify the disease, '
        'localize suspicious regions, and estimate severity.'
    )

    with gr.Row():
        input_image = gr.Image(
            type='numpy',
            label='Leaf Image'
        )

        output_image = gr.Image(
            type='numpy',
            label='Localization Result'
        )

    with gr.Row():
        disease_out = gr.Textbox(label='Disease / Class')
        conf_out = gr.Textbox(label='Confidence')
        severity_out = gr.Textbox(label='Estimated Severity')
        level_out = gr.Textbox(label='Severity Level')

    btn = gr.Button('Analyze')

    btn.click(
        dashboard_predict,
        inputs=input_image,
        outputs=[
            disease_out,
            conf_out,
            severity_out,
            level_out,
            output_image
        ]
    )

demo.launch(share=True)

"""## 12) نمودارهای آموزش"""

results_csv = f'runs/classify/{RUN_NAME}/results.csv'

if os.path.exists(results_csv):
    hist = pd.read_csv(results_csv)

    plt.figure(figsize=(10, 5))

    if 'train/loss' in hist.columns:
        plt.plot(
            hist['epoch'],
            hist['train/loss'],
            label='Train Loss'
        )

    if 'val/loss' in hist.columns:
        plt.plot(
            hist['epoch'],
            hist['val/loss'],
            label='Val Loss'
        )

    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.title('Training / Validation Loss')
    plt.legend()
    plt.tight_layout()
    plt.show()

    plt.figure(figsize=(10, 5))

    if 'metrics/accuracy_top1' in hist.columns:
        plt.plot(
            hist['epoch'],
            hist['metrics/accuracy_top1'],
            label='Top-1 Accuracy'
        )

    if 'metrics/accuracy_top5' in hist.columns:
        plt.plot(
            hist['epoch'],
            hist['metrics/accuracy_top5'],
            label='Top-5 Accuracy'
        )

    plt.xlabel('Epoch')
    plt.ylabel('Accuracy')
    plt.title('Accuracy')
    plt.legend()
    plt.tight_layout()
    plt.show()

else:
    print('results.csv پیدا نشد.')

"""## 13) ذخیره گزارش نهایی"""

report = classification_report(
    y_true,
    y_pred,
    target_names=class_names,
    output_dict=True,
    zero_division=0
)

report_df = pd.DataFrame(report).T

report_df.to_csv(
    f'{RUN_NAME}_classification_report.csv',
    encoding='utf-8-sig'
)

np.save(
    f'{RUN_NAME}_confusion_matrix.npy',
    cm
)

clean_df.to_csv(
    f'{RUN_NAME}_cleaning_report.csv',
    index=False,
    encoding='utf-8-sig'
)

split_df.to_csv(
    f'{RUN_NAME}_split_report.csv',
    index=False,
    encoding='utf-8-sig'
)

print('Saved:')
print(f'- {RUN_NAME}_classification_report.csv')
print(f'- {RUN_NAME}_confusion_matrix.npy')
print(f'- {RUN_NAME}_cleaning_report.csv')
print(f'- {RUN_NAME}_split_report.csv')
print(f'- {MODEL_PATH}')

